/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kcwiki.x.cic.plugin.impl.cicpanel.gui;

import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.Timer;
import javax.swing.border.Border;
import javax.swing.event.MouseInputListener;
import kcwiki.x.cic.cache.inmem.SystemData;
import kcwiki.x.cic.plugin.impl.cicpanel.entity.port.Port;
import kcwiki.x.cic.plugin.impl.cicpanel.entity.require_info.Require_info;

/**
 *
 * @author x5171
 * 
 */
public class CicPanel extends javax.swing.JFrame {

    private static final long serialVersionUID = -2027934260513523137L;
    private CicPanel cicPanel;
    /**
     * Creates new form Panel
     */
    public CicPanel() {
        initComponents();
        cicPanel = this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ttkinfo = new javax.swing.JPanel();
        ttkid_title = new javax.swing.JLabel();
        ttkname_title = new javax.swing.JLabel();
        ttklv_title = new javax.swing.JLabel();
        ttklv_value = new javax.swing.JLabel();
        ttkid_value = new javax.swing.JLabel();
        ttkname_value = new javax.swing.JLabel();
        ttkrank_title = new javax.swing.JLabel();
        ttkrank_value = new javax.swing.JLabel();
        ttkexp_title = new javax.swing.JLabel();
        ttkexp_value = new javax.swing.JLabel();
        ship_title = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        baseinfo = new javax.swing.JPanel();
        ammo_value = new javax.swing.JLabel();
        improvementmaterials_titel = new javax.swing.JLabel();
        bauxite_titel = new javax.swing.JLabel();
        improvementmaterials_value = new javax.swing.JLabel();
        bauxite_value = new javax.swing.JLabel();
        builditem_title = new javax.swing.JLabel();
        buckets_titel = new javax.swing.JLabel();
        builditem_value = new javax.swing.JLabel();
        buckets_value = new javax.swing.JLabel();
        fuel_titel = new javax.swing.JLabel();
        fastbuilditem_titel = new javax.swing.JLabel();
        fuel_value = new javax.swing.JLabel();
        fastbuilditem_value = new javax.swing.JLabel();
        steel_titel = new javax.swing.JLabel();
        steel_value = new javax.swing.JLabel();
        ammo_titel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ttkid_title.setText("提督ID");

        ttkname_title.setText("提督昵称");

        ttklv_title.setText("提督等级");

        ttklv_value.setText("0");

        ttkid_value.setText("0");

        ttkname_value.setText("0");

        ttkrank_title.setText("提督军衔");

        ttkrank_value.setText("0");

        ttkexp_title.setText("提督经验");

        ttkexp_value.setText("0");

        ship_title.setText("舰娘数量");

        jLabel14.setText("0");

        jLabel15.setText("装备数量");

        jLabel16.setText("0");

        javax.swing.GroupLayout ttkinfoLayout = new javax.swing.GroupLayout(ttkinfo);
        ttkinfo.setLayout(ttkinfoLayout);
        ttkinfoLayout.setHorizontalGroup(
            ttkinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ttkinfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ttkinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ttkinfoLayout.createSequentialGroup()
                        .addComponent(ttkid_title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ttkid_value))
                    .addGroup(ttkinfoLayout.createSequentialGroup()
                        .addComponent(ttklv_title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ttklv_value))
                    .addGroup(ttkinfoLayout.createSequentialGroup()
                        .addComponent(ship_title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14))
                    .addGroup(ttkinfoLayout.createSequentialGroup()
                        .addComponent(ttkrank_title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ttkrank_value)))
                .addGap(87, 87, 87)
                .addGroup(ttkinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ttkinfoLayout.createSequentialGroup()
                        .addComponent(ttkname_title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ttkname_value))
                    .addGroup(ttkinfoLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16))
                    .addGroup(ttkinfoLayout.createSequentialGroup()
                        .addComponent(ttkexp_title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ttkexp_value)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        ttkinfoLayout.setVerticalGroup(
            ttkinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ttkinfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ttkinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ttkinfoLayout.createSequentialGroup()
                        .addGroup(ttkinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ttkname_title)
                            .addComponent(ttkname_value))
                        .addGap(51, 51, 51)
                        .addGroup(ttkinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ttkexp_title)
                            .addComponent(ttkexp_value))
                        .addGap(18, 18, 18)
                        .addGroup(ttkinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)))
                    .addGroup(ttkinfoLayout.createSequentialGroup()
                        .addGroup(ttkinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ttkid_title)
                            .addComponent(ttkid_value))
                        .addGap(18, 18, 18)
                        .addGroup(ttkinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ttkrank_title)
                            .addComponent(ttkrank_value))
                        .addGap(18, 18, 18)
                        .addGroup(ttkinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ttklv_value)
                            .addComponent(ttklv_title))
                        .addGap(18, 18, 18)
                        .addGroup(ttkinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(ship_title))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        ttkid_title.getAccessibleContext().setAccessibleDescription("ttkid");

        ammo_value.setText("0");

        improvementmaterials_titel.setText("螺丝");

        bauxite_titel.setText("铝");

        improvementmaterials_value.setText("0");

        bauxite_value.setText("0");

        builditem_title.setText("资材");

        buckets_titel.setText("桶");

        builditem_value.setText("0");

        buckets_value.setText("0");

        fuel_titel.setText("油");

        fastbuilditem_titel.setText("喷火");

        fuel_value.setText("0");

        fastbuilditem_value.setText("0");

        steel_titel.setText("钢");

        steel_value.setText("0");

        ammo_titel.setText("弹");

        javax.swing.GroupLayout baseinfoLayout = new javax.swing.GroupLayout(baseinfo);
        baseinfo.setLayout(baseinfoLayout);
        baseinfoLayout.setHorizontalGroup(
            baseinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseinfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(baseinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(baseinfoLayout.createSequentialGroup()
                        .addComponent(builditem_title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(builditem_value))
                    .addGroup(baseinfoLayout.createSequentialGroup()
                        .addComponent(fuel_titel)
                        .addGap(18, 18, 18)
                        .addComponent(fuel_value))
                    .addGroup(baseinfoLayout.createSequentialGroup()
                        .addComponent(ammo_titel)
                        .addGap(18, 18, 18)
                        .addComponent(ammo_value))
                    .addGroup(baseinfoLayout.createSequentialGroup()
                        .addComponent(buckets_titel)
                        .addGap(18, 18, 18)
                        .addComponent(buckets_value)))
                .addGap(114, 114, 114)
                .addGroup(baseinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(baseinfoLayout.createSequentialGroup()
                        .addComponent(steel_titel)
                        .addGap(18, 18, 18)
                        .addComponent(steel_value))
                    .addGroup(baseinfoLayout.createSequentialGroup()
                        .addComponent(bauxite_titel)
                        .addGap(18, 18, 18)
                        .addComponent(bauxite_value))
                    .addGroup(baseinfoLayout.createSequentialGroup()
                        .addComponent(improvementmaterials_titel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(improvementmaterials_value))
                    .addGroup(baseinfoLayout.createSequentialGroup()
                        .addComponent(fastbuilditem_titel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fastbuilditem_value)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        baseinfoLayout.setVerticalGroup(
            baseinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseinfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(baseinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(baseinfoLayout.createSequentialGroup()
                        .addGroup(baseinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fuel_value, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fuel_titel))
                        .addGap(18, 18, 18)
                        .addGroup(baseinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ammo_titel)
                            .addComponent(ammo_value))
                        .addGap(18, 18, 18)
                        .addGroup(baseinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buckets_titel)
                            .addComponent(buckets_value))
                        .addGap(18, 18, 18)
                        .addGroup(baseinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(builditem_title)
                            .addComponent(builditem_value)))
                    .addGroup(baseinfoLayout.createSequentialGroup()
                        .addGroup(baseinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(steel_titel)
                            .addComponent(steel_value))
                        .addGap(18, 18, 18)
                        .addGroup(baseinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bauxite_titel)
                            .addComponent(bauxite_value))
                        .addGap(18, 18, 18)
                        .addGroup(baseinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(improvementmaterials_titel)
                            .addComponent(improvementmaterials_value))
                        .addGap(18, 18, 18)
                        .addGroup(baseinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fastbuilditem_titel)
                            .addComponent(fastbuilditem_value))))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(baseinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ttkinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ttkinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(baseinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CicPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CicPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CicPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CicPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CicPanel().setVisible(true);
            }
        });
    }
    
    public void updatePortData(kcwiki.x.cic.plugin.impl.cicpanel.entity.port.Api_data api_data) {
        ttkid_value.setText(String.valueOf(api_data.getApi_basic().getApi_member_id()));
        ttkname_value.setText(api_data.getApi_basic().getApi_nickname());
        ttklv_value.setText(String.valueOf(api_data.getApi_basic().getApi_level()));
        ttkrank_value.setText(SystemData.getRankList().get(api_data.getApi_basic().getApi_rank()));
        ttkexp_value.setText(String.valueOf(api_data.getApi_basic().getApi_experience()));
        
        fuel_value.setText(String.valueOf(api_data.getApi_material().get(0).getApi_value()));
        ammo_value.setText(String.valueOf(api_data.getApi_material().get(1).getApi_value()));
        steel_value.setText(String.valueOf(api_data.getApi_material().get(2).getApi_value()));
        bauxite_value.setText(String.valueOf(api_data.getApi_material().get(3).getApi_value()));
        fastbuilditem_value.setText(String.valueOf(api_data.getApi_material().get(4).getApi_value()));
        buckets_value.setText(String.valueOf(api_data.getApi_material().get(5).getApi_value()));
        builditem_value.setText(String.valueOf(api_data.getApi_material().get(6).getApi_value()));
        improvementmaterials_value.setText(String.valueOf(api_data.getApi_material().get(7).getApi_value()));
        
    }
    
    public void updateTTkData(kcwiki.x.cic.plugin.impl.cicpanel.entity.require_info.Api_data api_data) {
        ttkid_value.setText(String.valueOf(api_data.getApi_basic().getApi_member_id()));
    }
    
    public void createPanel(){
//        cicPanel.setUndecorated(true);
        cicPanel.setTitle("KanColle Combat Information Center");
        cicPanel.setResizable(false);
        cicPanel.setAlwaysOnTop(true);
        
        try{
//             ttkinfo.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createTitledBorder("提督信息"), BorderFactory.createEtchedBorder())); //设置面板边框，实现分组框的效果，此句代码为关键代码
//                ttkinfo.setBorder(BorderFactory.createLineBorder(Color.red));//设置面板边框颜色
                
                ttkinfo.setBorder(BorderFactory.createTitledBorder("提督信息")  );
                baseinfo.setBorder(BorderFactory.createTitledBorder("提督资源库")  );
                JPanel simpleBorder = new JPanel();
                
                Border emptyPanl, llineBorder, etchedBorder, raisedBorder, loweredBevelBorder, emptyBorder;
		emptyPanl = BorderFactory.createEmptyBorder(10, 10, 10, 10);
		llineBorder = BorderFactory.createLineBorder(Color.red);
		etchedBorder = BorderFactory.createEtchedBorder();
		raisedBorder = BorderFactory.createRaisedBevelBorder();
		loweredBevelBorder = BorderFactory.createLoweredBevelBorder();
		emptyBorder = BorderFactory.createEmptyBorder();
		simpleBorder.setBorder(emptyPanl);
		simpleBorder.setLayout(new BoxLayout(simpleBorder, BoxLayout.Y_AXIS));
		addCompForBorder(llineBorder,"line border",simpleBorder);
		addCompForBorder(etchedBorder,"etche border",simpleBorder);
		addCompForBorder(loweredBevelBorder,"lowere border",simpleBorder);
		addCompForBorder(emptyBorder,"empty border",simpleBorder);
		
		JTabbedPane jTabbedPane = new JTabbedPane();
		jTabbedPane.setToolTipText("simple");
		jTabbedPane.addTab("simple", simpleBorder);
		baseinfo.add(jTabbedPane);
                cicPanel.setVisible(true);
            }catch(Exception ex){
                
                System.err.print(ex);
            }
//        java.awt.EventQueue.invokeLater(() -> {
//            try{
//                ttkinfo.setBorder(BorderFactory.createTitledBorder("分组框")); //设置面板边框，实现分组框的效果，此句代码为关键代码
//                ttkinfo.setBorder(BorderFactory.createLineBorder(Color.red));//设置面板边框颜色
//                baseinfo.setBorder(BorderFactory.createTitledBorder("提督资源库")  );
//                JPanel simpleBorder = new JPanel();
//                
//                Border emptyPanl, llineBorder, etchedBorder, raisedBorder, loweredBevelBorder, emptyBorder;
//		emptyPanl = BorderFactory.createEmptyBorder(10, 10, 10, 10);
//		llineBorder = BorderFactory.createLineBorder(Color.red);
//		etchedBorder = BorderFactory.createEtchedBorder();
//		raisedBorder = BorderFactory.createRaisedBevelBorder();
//		loweredBevelBorder = BorderFactory.createLoweredBevelBorder();
//		emptyBorder = BorderFactory.createEmptyBorder();
//		simpleBorder.setBorder(emptyPanl);
//		simpleBorder.setLayout(new BoxLayout(simpleBorder, BoxLayout.Y_AXIS));
//		addCompForBorder(llineBorder,"line border",simpleBorder);
//		addCompForBorder(etchedBorder,"etche border",simpleBorder);
//		addCompForBorder(loweredBevelBorder,"lowere border",simpleBorder);
//		addCompForBorder(emptyBorder,"empty border",simpleBorder);
//		
//		JTabbedPane jTabbedPane = new JTabbedPane();
//		jTabbedPane.setToolTipText("simple");
//		jTabbedPane.addTab("simple", simpleBorder);
//		baseinfo.add(jTabbedPane);
//                cicPanel.setVisible(true);
//            }catch(Exception ex){
//                System.err.print(ex);
//            }
//        });
    }
    
    private void addCompForBorder(Border border,String lable,Container container) {
            //(1)
            JPanel comp = new JPanel(false);
            JLabel label = new JLabel(lable, JLabel.CENTER);
            comp.setLayout(new GridLayout(1, 1));
            comp.add(label);
            comp.setBorder(border);
 
	    container.add(Box.createRigidArea(new Dimension(0, 10)));
	    container.add(comp);
	}
    
    public void destroyPanel(){
        if (cicPanel == null)
            return;
        cicPanel.dispose();
        cicPanel = null;
    }
    
    
    class Drag implements MouseInputListener {
		int moving = 0;  //显示Panel是否处于移动过程中，否则只要单击便会调用press里面的方法
		int xinit = 0;	 //鼠标按下时所处的X坐标
		int yinit = 0;   //鼠标按下时所处的Y坐标
		int x0 = 0;		//拖拽过程中鼠标的位置
		int y0 = 0;
		Timer timer;
 
		@Override
		public void mouseClicked(MouseEvent e) {
			// TODO Auto-generated method stub
 
		}
 
		@Override
		public void mouseEntered(MouseEvent e) {
			// TODO Auto-generated method stub
 
		}
 
		@Override
		public void mouseExited(MouseEvent e) {
			// TODO Auto-generated method stub
 
		}
		
		//鼠标按下时初始化线程
		@Override
		public void mousePressed(MouseEvent e) {
			// TODO Auto-generated method stub
			xinit = e.getX();
			yinit = e.getY();
			timer = new Timer(10, new ActionListener() {
 
				public void actionPerformed(ActionEvent e) {
					// TODO Auto-generated method stub
					cicPanel.setBounds(x0 - xinit + baseinfo.getX(), y0 - yinit
							+ baseinfo.getY(), 100, 100);
				}
			});
		}
		
		//鼠标松开时结束线程
		@Override
		public void mouseReleased(MouseEvent e) {
			// TODO Auto-generated method stub
			if (moving == 1) {
				int x1 = e.getX();
				int y1 = e.getY();
				baseinfo.setBounds(x1 - xinit + baseinfo.getX(),
						y1 - yinit + baseinfo.getY(), 100, 100);
				moving = 0;
				baseinfo.setVisible(true);
				cicPanel.setVisible(false);
				timer.stop();
			}
		}
		
		//鼠标拖动过程中，不断更新maskPanel的位置
		@Override
		public void mouseDragged(MouseEvent arg0) {
			// TODO Auto-generated method stub
			x0 = arg0.getX();
			y0 = arg0.getY();
			if (x0 > baseinfo.getX() && x0 < (baseinfo.getX() + baseinfo.getWidth())
					&& y0 > baseinfo.getY()
					&& y0 < (baseinfo.getY() + baseinfo.getHeight())) {
				moving = 1;
				baseinfo.setVisible(false);
				cicPanel.setVisible(true);
				timer.start();
			}
 
		}
 
		@Override
		public void mouseMoved(MouseEvent arg0) {
			// TODO Auto-generated method stub
 
		}
 
	}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ammo_titel;
    private javax.swing.JLabel ammo_value;
    private javax.swing.JPanel baseinfo;
    private javax.swing.JLabel bauxite_titel;
    private javax.swing.JLabel bauxite_value;
    private javax.swing.JLabel buckets_titel;
    private javax.swing.JLabel buckets_value;
    private javax.swing.JLabel builditem_title;
    private javax.swing.JLabel builditem_value;
    private javax.swing.JLabel fastbuilditem_titel;
    private javax.swing.JLabel fastbuilditem_value;
    private javax.swing.JLabel fuel_titel;
    private javax.swing.JLabel fuel_value;
    private javax.swing.JLabel improvementmaterials_titel;
    private javax.swing.JLabel improvementmaterials_value;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel ship_title;
    private javax.swing.JLabel steel_titel;
    private javax.swing.JLabel steel_value;
    private javax.swing.JLabel ttkexp_title;
    private javax.swing.JLabel ttkexp_value;
    private javax.swing.JLabel ttkid_title;
    private javax.swing.JLabel ttkid_value;
    private javax.swing.JPanel ttkinfo;
    private javax.swing.JLabel ttklv_title;
    private javax.swing.JLabel ttklv_value;
    private javax.swing.JLabel ttkname_title;
    private javax.swing.JLabel ttkname_value;
    private javax.swing.JLabel ttkrank_title;
    private javax.swing.JLabel ttkrank_value;
    // End of variables declaration//GEN-END:variables
}
